'use-strict'

const ERROR_COLOR = '#FF377F'
const PRIMARY_COLOR = '#383E71'
const SECONDARY_COLOR = '#989FDB'
const WHITE_COLOR = '#FFFFFF'
const BLACK_COLOR = '#000000'

export default {
    BLACK_COLOR,
    ERROR_COLOR,
    PRIMARY_COLOR,
    SECONDARY_COLOR,
    WHITE_COLOR
}